config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cocktails#index'
  resources :cocktails, only: [:index, :show, :create, :new, :destroy] do
    resources :doses, only: [:show, :index, :new, :create]
    resources :reviews, only: [:show, :index, :new, :create]
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [ :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates_uniqueness_of :cocktail, scope: [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @reviews = @cocktail.reviews
    @review = Review.new
    @doses = @cocktail.doses
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(strong_params)
    redirect_to cocktails_path
  end

  private

  def strong_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @dose = Dose.new(strong_params)
    @dose[:cocktail_id] = params[:cocktail_id]
    @cocktail = Cocktail.find(params[:cocktail_id])
    return redirect_to @cocktail if @dose.save
    redirect_to @cocktail
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
    @cocktail = Cocktail.find(params[:cocktail_id])
    redirect_to @cocktail
  end

  private

  def strong_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(strong_params)
    @review[:cocktail_id] = params[:cocktail_id]
    @cocktail = Cocktail.find(params[:cocktail_id])
    return redirect_to @cocktail if @Review.save
    redirect_to @cocktail
  end

  def destroy
    @review = Review.find(params[:id])
    @review.delete
    @cocktail = Cocktail.find(params[:cocktail_id])
    redirect_to @cocktail
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form_cocktails.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://kitt.lewagon.com/placeholder/cities/berlin');">
  <div class="banner-content">
    <h1>Mr. Cocktail</h1>
    <p>Learn more about your favourite Cocktail</p>
    <%= link_to 'Add new cocktail', new_cocktail_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

<div class="container">

    <% @cocktails.each do |cocktail| %>
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
      <div class="card-category">Popular</div>
      <div class="card-description">
        <div class="col-xs-12 col-sm-4">
          <%= link_to cocktail.name, cocktail_path(cocktail), class: 'cocktail-name' %>
        </div>
      </div>
      <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
      <%= link_to "", cocktail_path(cocktail) %>
    </div>
    <% end %>

</div>

app/views/cocktails/new.html.erb
<%= render 'form_cocktails', cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<%= link_to 'Home', cocktails_path %>

<div class="container-show">
  <div class="recipe">
    <h2>Recipe</h2>
    <table>
      <thead>
        <tr>
          <th>Ingredient</th>
          <th>Description</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @doses.each do |dose| %>
        <tr>
          <td><%= dose.ingredient.name %></td>
          <td><%= dose.description %></td>
          <td><%= link_to 'Delete', dose_path(dose), method: :delete %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="create-dose">
    <h2>Add a new dose</h2>
    <%= render 'doses/new' %>
  </div>
</div>


<div class="reviews">
<% @reviews.each do |review| %>
<%= review.content %>
<% end %>
</div>


<%= render 'reviews/new' %>

app/views/doses/_doses.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/doses/_new.html.erb
<%= render 'doses/doses', dose: @dose, cocktail: @cocktail %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
  <div class="navbar-wagon">
    <!-- Logo -->
    <a href="/" class="navbar-wagon-brand">
      <img src="#" alt="logo">
    </a>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
      <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
      <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Host</a></li>
          <li><a href="#">Trips</a></li>
          <li><a href="#">Messagese</a></li>
        </ul>
      </div>
    </div>
  </div>

  <%= yield %>

  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This footer is made with <i class="fas fa-heart"></i> at Le Wagon
    </div>
  </div>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>
</body>
</html>

app/views/reviews/_new.html.erb
<%= render 'reviews/reviews', review: @review, cocktail: @cocktail %>

app/views/reviews/_reviews.html.erb
<%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating,
    collection: [0, 1, 2, 3, 4, 5] %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>